version: "3.9"

services:
  mongodb:
    container_name: mongodb_service
    image: "mongo:latest"
    networks:
      node-webapp-network:
        aliases:
          - "mongo-alias"
  redis:
    container_name: redis_service
    image: "redis:latest"
    networks:
      node-webapp-network:
        aliases:
          - "redis-alias"
  app:
    container_name: hello-wops
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - MONGO_HOST=mongo-alias
      - MONGO_PORT=27017
      - REDIS_HOST=redis-alias
      - REDIS_PORT=6379
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    networks:
      - node-webapp-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ./logs:/app/logs
networks:
  node-webapp-network:
    driver: bridge