version: "3.9"

services:
  mongodb:
    container_name: mongodb_service
    image: "mongo:latest"
    ports:
      - "27017:27017"
    networks:
      - node-webapp-network
  redis:
    container_name: redis_service
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - node-webapp-network
  app:
    container_name: hello-wops
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    networks:
      - node-webapp-network
networks:
  node-webapp-network:
    driver: bridge

    

